pipeline {
    agent any
    tools {
        nodejs 'v16' // Ensure that jenkins instance has a node installation named v16 (corresponds to Node v16.15.1)
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install redocly') {
            steps {
                script {
                    try {
                      sh "redocly --help"
                    } catch (Exception e) {
                      sh 'npm i -g @redocly/cli@latest'
                    }
                }
            }
        }
        stage('Lint') {
            steps {
                script {
                    def returnCode = sh(
                        returnStatus: true,
                        script: '''
                            cd openapi
                            chmod +x ./build.sh
                            ./build.sh
                        '''
                        )
                    if (returnCode == 1) {
                        echo "Validation failed with some errors."
                        sh 'false'
                    }
                }
            }
        }
    }
    post {
        always {
            notify {
                notificationChannels(['github'])
            }
        }
    }
}
